app_publication:
    resource: "@AppBundle/Resources/config/routing/publication.yml"
    prefix:   /publication

app_admin:
    resource: "routing/admin.yml"
    prefix:   /admin

app_public:
    resource: "routing/public.yml"

